FROM python:3.11-slim-bookworm AS base

# Avoid warnings by switching to noninteractive
ARG DEBIAN_FRONTEND=noninteractive

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

#RUN ulimit -s unlimited

#install libraries
#RUN apt-get -q update \
#    && apt-get -q -y install build-essential gfortran cmake libnetcdf-dev libnetcdff-dev  \
#    && apt-get -q clean \
#    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get -y install build-essential gfortran cmake libnetcdf-dev libnetcdff-dev

# installs common to builder & production
RUN pip install numpy scipy netCDF4 pyyaml progress pandas pytest requests SALib ftputil

COPY install.sh install.sh
COPY README.md README.md
COPY src src
RUN ./install.sh /hyfaa
ENV PATH /hyfaa:/hyfaa/bin:${PATH}
ENV PYTHONPATH /hyfaa/lib/python3.11/site-packages:${PYTHONATH}

RUN mkdir /work
WORKDIR /work

CMD ["/bin/bash", "run.sh"]


